name: Build App AnimeYarn

on:
    push:
        branches:
            - developer

jobs:
    build_android_app:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            discussions: write

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Setup java
              uses: actions/setup-java@v3.6.0
              with:
                  distribution: adopt
                  java-version: 11

            - name: Setup gradle
              uses: gradle/gradle-build-action@v2.3.3

            - name: Install tabris-cli
              run: npm install -g tabris-cli

            - name: Install application dependencies
              run: |
                  npm run --if-present prepare
                  npm install

            - name: Execute buildp
              run: |
                  tabris build --release android -- --packageType=apk
            - name: Sign release
              uses: NoCrypt/sign-android@main
              id: sign_app
              with:
                  releaseDir: build/cordova/platforms/android/app/build/outputs/apk/release
                  signingKey: ${{ secrets.ANDROID_APP_BUNDLE_SIGNING_KEY }}
                  keyStorePassword: ${{ secrets.ANDROID_APP_BUNDLE_KEYSTORE_PASSWORD }}
                  keyAlias: ${{ secrets.ANDROID_APP_BUNDLE_KEY_ALIAS }}
                  keyPassword: ${{ secrets.ANDROID_APP_BUNDLE_KEY_PASSWORD }}
                  
            - name: Store signed app bundle
              uses: actions/upload-artifact@v4
              with:
                  name: signed-app-bundle
                  path: |
                    ${{ steps.sign_app.outputs.signedFile }}
                  retention-days: 7
            - name: Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "0.1.6"
                  prerelease: false
                  title: "Release"
                  files: |
                      ${{ steps.sign_app.outputs.signedFile }}
