name: "Secretos de Entorno"

on:
  push:
    branches:
      - 'exports'

jobs:
  exported-vars:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: secrets action
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TABRIS_BUILD_KEY, ANDROID_APP*
      - name: show secrets
        run: echo "$TABRIS_BUILD_KEY"
